// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIGhTPfLXljTZvrHiGxr4u2ytTuBeYfX8',
    appId: '1:261555270326:web:9a9620d3dbaf46d8aaec17',
    messagingSenderId: '261555270326',
    projectId: 'loginauth-44050',
    authDomain: 'loginauth-44050.firebaseapp.com',
    storageBucket: 'loginauth-44050.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRNRuCSnHsOlrYnuy8j4J13DP3tlPCdpg',
    appId: '1:261555270326:android:55bc2c9e3727b2cdaaec17',
    messagingSenderId: '261555270326',
    projectId: 'loginauth-44050',
    storageBucket: 'loginauth-44050.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2JIkkg5KjOjBzFaQY59VaB-SEjj8EQs',
    appId: '1:261555270326:ios:f20bdf1897d8fcc3aaec17',
    messagingSenderId: '261555270326',
    projectId: 'loginauth-44050',
    storageBucket: 'loginauth-44050.firebasestorage.app',
    iosBundleId: 'com.example.loginauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2JIkkg5KjOjBzFaQY59VaB-SEjj8EQs',
    appId: '1:261555270326:ios:f20bdf1897d8fcc3aaec17',
    messagingSenderId: '261555270326',
    projectId: 'loginauth-44050',
    storageBucket: 'loginauth-44050.firebasestorage.app',
    iosBundleId: 'com.example.loginauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIGhTPfLXljTZvrHiGxr4u2ytTuBeYfX8',
    appId: '1:261555270326:web:ca630a17209365afaaec17',
    messagingSenderId: '261555270326',
    projectId: 'loginauth-44050',
    authDomain: 'loginauth-44050.firebaseapp.com',
    storageBucket: 'loginauth-44050.firebasestorage.app',
  );
}
